copyright: © 2014 <a href="http://joyneop.github.io/">Joy Neop</a>. All Rights Reserved.
title: Implementing a Static Blog System
brief: A simple and easy tutorial for beginners
author: Joy Neop
year: 2014
language: en