copyright: © 2015 <a href="http://joyneop.github.io/">Joy Neop</a>. All Rights Reserved.
title: Lorem ipsum dolor sit amet
brief: I jump over the lazy doge; it doesn't hurt me.
author: Joy Neop
year: 2015
language: en
